version: '3.7'

services:
  backend:
    build: ./backend
    container_name: trackerlora_back
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - trackerlora_trackerlora
networks:
  trackerlora_trackerlora:
    external: true
    name: trackerlora_trackerlora
