version: '3.7'

services:
  backend:
    build: ./backend
    container_name: trackerlora_back
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - trackerlora_trackerlora
    # environment:
    #   - server.port='8080'
    #   - spring.datasource.password='aspitasaspitas2'
    #   - spring.datasource.username=root
    #   - spring.datasource.url= 'jdbc:postgresql://192.168.1.62:5432/trackerlora'
    logging:
      driver: fluentd
      options:
        fluentd-address: lopezcarrillo.com:12345
networks:
  trackerlora_trackerlora:
    external: true
    name: trackerlora_trackerlora
